<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Product>DotMake Svg-Sprite Cli</Product>
    <AssemblyName>svg-sprite</AssemblyName>

    <PackAsTool>true</PackAsTool>
    <ToolCommandName>svg-sprite</ToolCommandName>
    <!-- NuGet Package Information (common ones are in Directory.Build.props) -->
    <!-- Description is used for assembly and NuGet metadata -->
    <Description>A dotnet tool for building or extracting of an SVG sprite, i.e. a .svg file with child &lt;symbol&gt; tags.</Description>
    <PackageTags>svg sprite symbol icon builder generator extractor dotnet tool cli</PackageTags>
    <PackageReleaseNotes>
      <![CDATA[
        - **Improved:** Updated `DotMake.CommandLine` to `v3.7.0`.
          Note that option short aliases for `svg-sprite build` and `svg-sprite extract` commands are changed:
          All are now single character e.g. `-O` and not `-oe` for `--overwrite-existing`.

        - **Improved:** Updated target framework for the tool to `net8.0`
          and also added `net8.0` as additional target framework to the library.

        - **Improved:** Strong name sign the DLLs for NuGet package. Signing will be done only when `DotMake.snk` exists,
          it's not committed to this repository.
      ]]>
    </PackageReleaseNotes>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DotMake.SvgSprite\DotMake.SvgSprite.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DotMake.CommandLine" Version="3.7.0" />
    <PackageReference Include="Glob.cs" Version="5.1.1643" />
  </ItemGroup>

</Project>
