<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;netstandard2.0</TargetFrameworks>
    <LangVersion>10.0</LangVersion>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>

    <!-- NuGet Package Information (common ones are in Directory.Build.props) -->
    <!-- Description is used for assembly and NuGet metadata -->
    <Description>A library for building or extracting of an SVG sprite, i.e. a .svg file with child &lt;symbol&gt; tags.</Description>
    <PackageTags>svg sprite symbol icon builder generator extractor dotnet library</PackageTags>
    <PackageReleaseNotes>
      <![CDATA[
        - **Improved:** Added `net8.0` as additional target framework to the library.

        - **Improved:** Strong name sign the DLLs for NuGet package. Signing will be done only when `DotMake.snk` exists,
          it's not committed to this repository.
      ]]>
    </PackageReleaseNotes>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\PreviewPageTemplate.html" />
  </ItemGroup>

</Project>
