<Project>

  <PropertyGroup>
    <!-- AssemblyTitle needs to be set in .targets which is imported after .csproj -->
    <AssemblyTitle Condition="'$(OutputType)' != 'Exe'">$(AssemblyName) ($(TargetFramework))</AssemblyTitle>
  </PropertyGroup>

  <!--
    We don't want SourceRevisionId appended to InformationalVersion mainly because shfb uses this attribute in assembly 
    for api docs (which is ugly) so we save SourceRevisionId as AssemblyMetadata instead.
    By the way using the default way below, does not work because it disables sourcelink all together? 
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    SourceRevisionId comes empty in that case.
    <InformationalVersion>$(Version)</InformationalVersion> (Reset it to the original value)
    Update: We no longer use shfb for docs so not needed for now.
  -->
  <!--
  <Target Name="SetCustomAssemblyMetadata" AfterTargets="InitializeSourceControlInformation" BeforeTargets="GetAssemblyAttributes">
    <ItemGroup>
      <AssemblyMetadata Include="RepositoryCommit" Value="$(SourceRevisionId)" />
    </ItemGroup>
    <PropertyGroup>
      <InformationalVersion>$(Version)</InformationalVersion>
    </PropertyGroup>
  </Target>
  -->

  
</Project>
